name: create_dart_library
description: belajar bikin library
version: 1.5.0
homepage: https://www.programmerzamannow.com
repository: https://github.com/aprxty3/create_dart_library.git

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
